# MacPorts Installer addition on 2014-05-05_at_23:51:02: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.
# Node v8 path fix for homebrew
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
export PATH="/usr/local/opt/node@8/bin:$PATH"

# Open a new tab in the current working directory
function tab() {
  osascript 2>/dev/null <<EOF
    tell application "System Events"
      tell process "Terminal" to keystroke "t" using command down
    end
    tell application "Terminal"
      activate
      do script with command "cd \"$PWD\"; $*" in window 1
    end tell
EOF
}

# Make history larger and available in all sessions
HISTSIZE=9000
HISTFILESIZE=$HISTSIZE
HISTCONTROL=ignorespace:ignoredups

history() {
  _bash_history_sync
  builtin history "$@"
}

_bash_history_sync() {
  builtin history -a         #1
  HISTFILESIZE=$HISTSIZE     #2
  #builtin history -c         #3
  #builtin history -r         #4
}

PROMPT_COMMAND=_bash_history_sync

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /usr/local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh

export HOST=$(ifconfig en0 | grep 'inet ' | cut -f2 | awk '{print($2)}')
echo "HOST set to $HOST"

echo "Setting colorful terminal :)"

export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

# disable XOF (so i-search ctrl+s works)
stty -ixon

echo "Ready, welcome Andrei"

# include shortcut file
if [ -f $HOME/.bash_aliases ]; then
    . $HOME/.bash_aliases
fi


# include docker alias file if it exists
if [ -f $HOME/.docker-alias ]; then
    . $HOME/.docker-alias
fi

##
# Your previous /Users/andreimiclaus/.profile file was backed up as /Users/andreimiclaus/.profile.macports-saved_2016-09-06_at_11:26:55
##

# MacPorts Installer addition on 2016-09-06_at_11:26:55: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

# add brew bash-completion - for docker, compose, machine etc.
if [ -f $(brew --prefix)/etc/bash_completion ]; then  
. $(brew --prefix)/etc/bash_completion
fi  
