
" powerline
set rtp+=/usr/local/lib/python3.7/site-packages/powerline/bindings/vim
set laststatus=2
set t_Co=256

set backspace=indent,eol,start
set autowrite
"colorscheme monokai-phoenix
"execute pathogen#infect()
filetype plugin indent on
au BufRead,BufNewFile *.ts setlocal filetype=javascript
syntax on
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
